#!/bin/bash

colorOff="\033[0m"
redBold="\e[31m\e[1m"
greenBold="\e[32m\e[1m"

echo "Running tests and trying to build before commit..."
echo "If the tests or the build fail, the commit will be aborted."

mvnResult=$(mvn clean package)

if [ $? -ne 0 ]
  then
  printf "${redBold}Tests or build failed. The commit was aborted.${colorOff}\n"
  echo
  exit 1
else
  printf "${greenBold}The tests passed and the build was successfull.${colorOff}\n"
  echo
fi
